global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
          
# Node Exporter (Optional)
# Uncomment when ready to collect host system metrics    
#  - job_name: "node"
#    static_configs:
#      - targets: ["node_exporter:9100"]          
#
# cAdvisor (Optional)
#  - job_name: "cadvisor"
#    static_configs:
#      - targets: ["cadvisor:8080"]









  # Add additional scrape jobs below if needed

  # Typical next jobs you’ll add (for context)
  # Later you’ll add jobs like:
  # cadvisor
  # home-assistant
  # pihole
  # Each one = one scrape job.
